# Top level keys are considered kernels
linux:
  # Kernels have global options for each of their flavours, these params will be
  # overriden with their flavor counterpart (if provided)

  # in kernel: optional, in flavor: optional
  cmdline: /path/to/cmdline

  # in kernel: optiona, in flavor: optional
  # fallbacks to /vmlinuz-{kernel}
  linux: /boot/vmlinuz-linux

  # in kernel: optional, in flavor: optional
  splash-image: /path/to/splash

  # in kernel: optional, in flavor: optional
  # fallbacks to /usr/lib/systemd/boot/efi/linuxx64.efi.stub
  efistub: /path/to/efistub

  # Flavors may have different options, different from global kernel options
  # Each kernel-flavor pair is referred as "kernel.flavor"
  #   - Match every kernel.flavor that starts with 'linux'
  #       genuki from-config "^linux"
  #   - Match every kernel.flavor that contains 'linux' in it
  #       genuki from-config "linux"
  #   - Match every kernel.flavor which kernel is 'linux'
  #       genuki from-config "linux\."
  #   - Match every kernel.flavor which flavor is 'fallback'
  #       genuki from-config ".*\.fallback"
  #
  # For more info about genuki regex syntax see:
  # https://docs.rs/regex/1/regex/index.html#syntax

  flavors:
    # Each key is a custom flavor

    default: # Referred as linux.default
      # Optional
      # Fallbacks to /etc/os-release, if not found
      # Fallbacks to /usr/lib/os-release
      os-release: /etc/os-release

      # Optional
      cmdline: /path/to/cmdline

      # Optional
      # If not provided will search for microcode and preprend it to
      # main initramfs based on kernel (and flavor if it's 'fallback')
      # Otherwise it'll combine in order the provided images.
      initrd:
        - /boot/intel-ucode.img
        - /boot/initramfs-linux.img

      # Required
      output: /boot/EFI/Arch/archlinux.efi

    fallback: # Referred as linux.fallback
      # Optional
      # Creates a temp file based on the provided file by 'os-release' with
      # PRETTY_NAME replaced, if 'os-release' is not provided it fallbacks
      # to /etc/os-release as shown above, otherwise uses provided file as base.
      title: "Arch Linux (fallback)"

      # Optional
      # It's also possible to provide the inline contents for cmdline, like this
      cmdline:
        inline: | # multi line string in yaml
          some kernel params here

      # Optional
      # Example of single value for initrd
      initrd: /boot/initramfs-linux-fallback.img

      # Required
      output: /boot/EFI/Arch/archlinux-fallback.efi # required
